---
name: Net-Amazon-AWIS
version: 0.33
author:
  - 'Leon Brocard C<acme@astray.com>'
abstract: Use the Amazon Alexa Web Information Service
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Accessor::Fast: 0
  DateTime::Format::Strptime: 0
  Digest::HMAC_SHA1: 0
  IO::Prompt: 0
  LWP::UserAgent: 0
  Module::Build: 0
  Test::Exception: 0.15
  Test::More: 0.01
  XML::LibXML: 0
  XML::LibXML::XPathContext: 0
provides:
  Net::Amazon::AWIS:
    file: lib/Net/Amazon/AWIS.pm
    version: 0.33
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
