--- #YAML:1.0
name: Net-Amazon-AWIS
version: 0.32
author:
  - Leon Brocard C<acme@astray.com>
abstract: Use the Amazon Alexa Web Information Service
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
